# Generated by Django 4.0.4 on 2022-08-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Staff',
        ),
    ]
