# Generated by Django 4.0.4 on 2022-08-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_rename_model_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
