# Generated by Django 4.0.4 on 2022-09-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_staff_feedback_feedback_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='feedback_reply',
        ),
    ]
