# Generated by Django 4.0.4 on 2022-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_remove_staff_feedback_feedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
    ]
