# Generated by Django 4.0.4 on 2022-09-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_alter_staff_feedback_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Feedback',
            new_name='Student_Feedback_Save',
        ),
    ]
