# Generated by Django 4.0.4 on 2022-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_rename_student_feedback_student_feedback_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback_save',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
