# Generated by Django 4.0.4 on 2022-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_student_feedback_save_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
