# Generated by Django 4.0.4 on 2022-09-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
