# Generated by Django 4.0.4 on 2022-09-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_rename_subject_id_attendance_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
